version: '3'

services:

  server:
    build: ./server
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ./server/src:/srv/app/vault-server/src
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    command: npm run docker

  client:
    build: ./client
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/srv/app/vault-client/src
      - ./client/public:/srv/app/vault-client/public
    links:
      - server
    command: npm start
    
  redis:
    image: redis
    expose:
      - "6379"

  mongo:
    image: mongo
    expose:
      - "27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin